### ISSUE TITLE
deflator uses deprecated Rack::Utils::HeaderHash

### ISSUE THREAD

**Issue by neongrau** [marcotc/rack-brotli#13]
See https://github.com/cyu/rack-cors/issues/251

just omitting the line 

```ruby
headers = Rack::Utils::HeaderHash.new(headers)
```

in `lib/rack/brotli/deflater.rb `
will fix this as it's not needed anymore.

**Comment by marcotc** [comment]
Thank you for your patience, @neongrau. This should be now implemented in [2.0.0](https://github.com/marcotc/rack-brotli/releases/tag/v2.0.0).
