### ISSUE TITLE
GPLv3 licensed runtime requirement: git-version-bump

### ISSUE THREAD

**Issue by livedo** [marcotc/rack-brotli#5]
The GPLv3 licensed https://github.com/mpalmer/git-version-bump is required as a runtime requirement in the gemspec. MIT is not compatible with GPLv3.

It's used in `Rack::Brotli#release`, which in turn doesn't appear to be used elsewhere. Can it be made a dev dependency?

**Comment by marcotc** [comment]
Thank you so much for pointing this out, @livedo.

I'll address it, and also review all dependencies, thanks again 🙇.

**Comment by marcotc** [comment]
👋 @livedo, [1.1.0](https://github.com/marcotc/rack-brotli/blob/v1.1.0/CHANGELOG.md#110) has been released without a dependency on `git-version-bump`.

I'm closing this issue now, thank you again for reporting it in first place!
