### ISSUE TITLE
Add to readme that on standard Rails apps with Rack, to use...

### ISSUE THREAD

**Issue by nuclearspike** [marcotc/rack-brotli#7]
in

application.rb

add "config.middleware.use Rack::Brotli"

directly under "config.middleware.use Rack::Deflater"

to get it to work. Why would the readme not have the most (or at least one of the most) configurations and how to set it up. 

This should be in the readme!

**Comment by marcotc** [comment]
This is now documented! Thank you for your patience, @nuclearspike.
